language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '8'

script: yarn run validate
after_success: 
  - npx codecov
  - yarn run release

branches:
  only:
    - master